version: "3.8"

services:
  api:
    container_name: evolution_api_test
    image: evoapicloud/evolution-api:latest
    # restart: always
    # depends_on:
    #   - redis
    #   - evolution-postgres
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - dokploy-network
    env_file:
      - .env
    expose:
      - "8080"

volumes:
  evolution_instances:

networks:
  dokploy-network:
    external: true